package my.recipecalculator;

import java.awt.event.ActionListener;

// Developed By: Edwin Kim
// ReciCalcView.java: Creates the look and feel of the GUI.

public class ReciCalcView extends javax.swing.JFrame 
{
	private static final long serialVersionUID = -3989915152191228831L;
    
    public ReciCalcView() 
    {
        initComponents();
    }

    // initComponents() was generated by the NetBeans GUI builder.
    // However, I edited a few lines to implement the action listeners in the controller instead of the view.
    private void initComponents() 
    {
        TypeGroup = new javax.swing.ButtonGroup();
        ingredientAdd = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        ingredientName = new javax.swing.JTextField();
        ingredientCost = new javax.swing.JTextField();
        Produce = new javax.swing.JRadioButton();
        Meat = new javax.swing.JRadioButton();
        Pantry = new javax.swing.JRadioButton();
        Organic = new javax.swing.JCheckBox();
        addIngredient = new javax.swing.JButton();
        clearIngredient = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        listAllButton = new javax.swing.JButton();
        calculateRecipe = new javax.swing.JPanel();
        ingredientLabel1 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        ingredientLabel2 = new javax.swing.JLabel();
        amount2 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        ingredientLabel3 = new javax.swing.JLabel();
        amount3 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        ingredientLabel4 = new javax.swing.JLabel();
        amount4 = new javax.swing.JTextField();
        name4 = new javax.swing.JTextField();
        ingredientLabel5 = new javax.swing.JLabel();
        amount5 = new javax.swing.JTextField();
        name5 = new javax.swing.JTextField();
        ingredientLabel6 = new javax.swing.JLabel();
        amount6 = new javax.swing.JTextField();
        name6 = new javax.swing.JTextField();
        ingredientLabel7 = new javax.swing.JLabel();
        amount7 = new javax.swing.JTextField();
        name7 = new javax.swing.JTextField();
        ingredientLabel8 = new javax.swing.JLabel();
        amount8 = new javax.swing.JTextField();
        name8 = new javax.swing.JTextField();
        ingredientLabel9 = new javax.swing.JLabel();
        amount9 = new javax.swing.JTextField();
        name9 = new javax.swing.JTextField();
        ingredientLabel10 = new javax.swing.JLabel();
        amount10 = new javax.swing.JTextField();
        name10 = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        clearRecipe = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        ingredientNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recipe Calculator");

        ingredientAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Ingredient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
        		javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(51, 51, 255)));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        nameLabel.setText("Name:");

        costLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        costLabel.setText("Cost:");

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        typeLabel.setText("Type:");

        TypeGroup.add(Produce);
        Produce.setText("Produce");

        TypeGroup.add(Meat);
        Meat.setText("Meat or Poultry");

        TypeGroup.add(Pantry);
        Pantry.setText("Pantry");

        Organic.setText("Organic");

        addIngredient.setFont(new java.awt.Font("Tahoma", 0, 12));
        addIngredient.setText("Add");

        clearIngredient.setFont(new java.awt.Font("Tahoma", 0, 12));
        clearIngredient.setText("Clear");

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        deleteButton.setText("Delete");

        deleteAllButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        deleteAllButton.setText("Delete All");

        listAllButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listAllButton.setText("List All");

        javax.swing.GroupLayout ingredientAddLayout = new javax.swing.GroupLayout(ingredientAdd);
        ingredientAdd.setLayout(ingredientAddLayout);
        ingredientAddLayout.setHorizontalGroup(
            ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(typeLabel)
                    .addComponent(costLabel))
                .addGap(18, 18, 18)
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingredientAddLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(addIngredient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearIngredient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listAllButton))
                    .addComponent(Pantry)
                    .addComponent(Meat)
                    .addComponent(Produce)
                    .addGroup(ingredientAddLayout.createSequentialGroup()
                        .addComponent(ingredientName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Organic))
                    .addComponent(ingredientCost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        ingredientAddLayout.setVerticalGroup(
            ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingredientAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(ingredientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Organic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costLabel))
                .addGap(8, 8, 8)
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Produce)
                    .addComponent(typeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Meat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pantry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(ingredientAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addIngredient)
                    .addComponent(clearIngredient)
                    .addComponent(deleteButton)
                    .addComponent(deleteAllButton)
                    .addComponent(listAllButton))
                .addContainerGap())
        );

        calculateRecipe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculate Recipe Cost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(51, 0, 255))); // NOI18N

        ingredientLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel1.setText("Ingredient 1:");

        ingredientLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel2.setText("Ingredient 2:");

        ingredientLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel3.setText("Ingredient 3:");

        ingredientLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel4.setText("Ingredient 4:");

        ingredientLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel5.setText("Ingredient 5:");

        ingredientLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel6.setText("Ingredient 6:");

        ingredientLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel7.setText("Ingredient 7:");

        ingredientLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel8.setText("Ingredient 8:");

        ingredientLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel9.setText("Ingredient 9:");

        ingredientLabel10.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientLabel10.setText("Ingredient 10:");

        calculateButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        calculateButton.setText("Calculate");

        clearRecipe.setFont(new java.awt.Font("Tahoma", 0, 12));
        clearRecipe.setText("Clear");

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        amountLabel.setText("Amount");

        ingredientNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ingredientNameLabel.setText("Name of Ingredient");

        javax.swing.GroupLayout calculateRecipeLayout = new javax.swing.GroupLayout(calculateRecipe);
        calculateRecipe.setLayout(calculateRecipeLayout);
        calculateRecipeLayout.setHorizontalGroup(
            calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculateRecipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calculateButton)
                            .addGroup(calculateRecipeLayout.createSequentialGroup()
                                .addComponent(ingredientLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(amount10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearRecipe)))
                    .addGroup(calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingredientLabel5)
                            .addComponent(ingredientLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calculateRecipeLayout.createSequentialGroup()
                                .addComponent(amount4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(calculateRecipeLayout.createSequentialGroup()
                                .addComponent(amount5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculateRecipeLayout.createSequentialGroup()
                        .addComponent(ingredientLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(calculateRecipeLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(amountLabel)
                .addGap(169, 169, 169)
                .addComponent(ingredientNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calculateRecipeLayout.setVerticalGroup(
            calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculateRecipeLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientNameLabel)
                    .addComponent(amountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel1))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel2))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel3))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel4))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel5))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel6))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientLabel7)
                    .addComponent(amount7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel8))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel9))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientLabel10))
                .addGap(18, 18, 18)
                .addGroup(calculateRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearRecipe)
                    .addComponent(calculateButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calculateRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingredientAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingredientAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    // These methods allow the program to implement the action listeners in the controller instead of the view.
    void addIngredientListener(ActionListener l)
    {
    	addIngredient.addActionListener(l);
    }
    
    void clearIngredientListener(ActionListener l)
    {
    	clearIngredient.addActionListener(l);
    }
    
    void deleteIngredientListener(ActionListener l)
    {
    	deleteButton.addActionListener(l);
    }
    
    void deleteAllListener(ActionListener l)
    {
    	deleteAllButton.addActionListener(l);
    }
    
    void listAllListener(ActionListener l)
    {
    	listAllButton.addActionListener(l);
    }
    
    void calculateListener(ActionListener l)
    {
    	calculateButton.addActionListener(l);
    }
    
    void clearRecipeListener(ActionListener l)
    {
    	clearRecipe.addActionListener(l);
    }
    
    
    // All the relevant information fetched from the GUI. This information is used in the controller.
    public String getIngredientName()
    {
        String name = ingredientName.getText();
        return name;
    }
    
    public String getIngredientCost()
    {
        String cost = ingredientCost.getText();
        return cost;
    }
    
    public boolean isOrganic()
    {
        boolean isOrganic = Organic.isSelected();
        return isOrganic;
    }
    
    public boolean isProduce()
    {
        boolean isProduce = Produce.isSelected();
        return isProduce;
    }
    
    public boolean isMeat()
    {
        boolean isMeat = Meat.isSelected();
        return isMeat;
    }
    
    public boolean isPantry()
    {
        boolean isPantry = Pantry.isSelected();
        return isPantry;
    }
    
    public void clearName()
    {
    	ingredientName.setText("");
    }
    
    public void clearCost()
    {
    	ingredientCost.setText("");
    }
    
    public void clearOrganic()
    {
    	Organic.setSelected(false);
    }
    
    public void clearType()
    {
    	TypeGroup.clearSelection();
    }
    
    public String getAmount1()
    {
    	String s = amount1.getText();
    	return s;
    }
    
    public String getAmount2()
    {
    	String s = amount2.getText();
    	return s;
    }
    
    public String getAmount3()
    {
    	String s = amount3.getText();
    	return s;
    }
    
    public String getAmount4()
    {
    	String s = amount4.getText();
    	return s;
    }
    
    public String getAmount5()
    {
    	String s = amount5.getText();
    	return s;
    }
    
    public String getAmount6()
    {
    	String s = amount6.getText();
    	return s;
    }
    
    public String getAmount7()
    {
    	String s = amount7.getText();
    	return s;
    }
    
    public String getAmount8()
    {
    	String s = amount8.getText();
    	return s;
    }
    
    public String getAmount9()
    {
    	String s = amount9.getText();
    	return s;
    }
    
    public String getAmount10()
    {
    	String s = amount10.getText();
    	return s;
    }
    
    public String getName1()
    {
    	String s = name1.getText();
    	return s;
    }
    
    public String getName2()
    {
    	String s = name2.getText();
    	return s;
    }
    
    public String getName3()
    {
    	String s = name3.getText();
    	return s;
    }
    
    public String getName4()
    {
    	String s = name4.getText();
    	return s;
    }
    
    public String getName5()
    {
    	String s = name5.getText();
    	return s;
    }
    
    public String getName6()
    {
    	String s = name6.getText();
    	return s;
    }
    
    public String getName7()
    {
    	String s = name7.getText();
    	return s;
    }
    
    public String getName8()
    {
    	String s = name8.getText();
    	return s;
    }
    
    public String getName9()
    {
    	String s = name9.getText();
    	return s;
    }
    
    public String getName10()
    {
    	String s = name10.getText();
    	return s;
    }
    
    public void clearAmount1()
    {
    	amount1.setText("");
    }
    
    public void clearAmount2()
    {
    	amount2.setText("");
    }
    
    public void clearAmount3()
    {
    	amount3.setText("");
    }
    
    public void clearAmount4()
    {
    	amount4.setText("");
    }
    
    public void clearAmount5()
    {
    	amount5.setText("");
    }
    
    public void clearAmount6()
    {
    	amount6.setText("");
    }
    
    public void clearAmount7()
    {
    	amount7.setText("");
    }
    
    public void clearAmount8()
    {
    	amount8.setText("");
    }
    
    public void clearAmount9()
    {
    	amount9.setText("");
    }
    
    public void clearAmount10()
    {
    	amount10.setText("");
    }
    
    public void clearName1()
    {
    	name1.setText("");
    }
    
    public void clearName2()
    {
    	name2.setText("");
    }
    
    public void clearName3()
    {
    	name3.setText("");
    }
    
    public void clearName4()
    {
    	name4.setText("");
    }
    
    public void clearName5()
    {
    	name5.setText("");
    }
    
    public void clearName6()
    {
    	name6.setText("");
    }
    
    public void clearName7()
    {
    	name7.setText("");
    }
    
    public void clearName8()
    {
    	name8.setText("");
    }
    
    public void clearName9()
    {
    	name9.setText("");
    }
    
    public void clearName10()
    {
    	name10.setText("");
    }

    // Variable declarations
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearRecipe;
    private javax.swing.JButton listAllButton;
    private javax.swing.JRadioButton Meat;
    private javax.swing.JCheckBox Organic;
    private javax.swing.JRadioButton Pantry;
    private javax.swing.JRadioButton Produce;
    private javax.swing.ButtonGroup TypeGroup;
    private javax.swing.JButton addIngredient;
    private javax.swing.JTextField amount1;
    private javax.swing.JTextField amount10;
    private javax.swing.JTextField amount2;
    private javax.swing.JTextField amount3;
    private javax.swing.JTextField amount4;
    private javax.swing.JTextField amount5;
    private javax.swing.JTextField amount6;
    private javax.swing.JTextField amount7;
    private javax.swing.JTextField amount8;
    private javax.swing.JTextField amount9;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JPanel calculateRecipe;
    private javax.swing.JButton clearIngredient;
    private javax.swing.JLabel costLabel;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel ingredientAdd;
    private javax.swing.JTextField ingredientCost;
    private javax.swing.JLabel ingredientLabel1;
    private javax.swing.JLabel ingredientLabel10;
    private javax.swing.JLabel ingredientLabel2;
    private javax.swing.JLabel ingredientLabel3;
    private javax.swing.JLabel ingredientLabel4;
    private javax.swing.JLabel ingredientLabel5;
    private javax.swing.JLabel ingredientLabel6;
    private javax.swing.JLabel ingredientLabel7;
    private javax.swing.JLabel ingredientLabel8;
    private javax.swing.JLabel ingredientLabel9;
    private javax.swing.JTextField ingredientName;
    private javax.swing.JLabel ingredientNameLabel;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name10;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField name4;
    private javax.swing.JTextField name5;
    private javax.swing.JTextField name6;
    private javax.swing.JTextField name7;
    private javax.swing.JTextField name8;
    private javax.swing.JTextField name9;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel typeLabel;
}